GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/persons/5

### -------------- Delete test
DELETE http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/persons

### POST Tests
POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "John Doe",
	"number": "12-34-567890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###